import { Metadata } from "next";
import { cookies } from "next/headers";
import React, { Suspense } from "react";

import { AntdRegistry } from "@ant-design/nextjs-registry";
// TODO: Verificar
import "@refinedev/antd/dist/reset.css";

import { RefineContext } from "./_refine_context";
import "../client/styles/global.css";

export const metadata: Metadata = {
  description: "Generated by Mochipan",
  icons: {
    icon: "/favicon.ico",
  },
  title: "Formel",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = cookies();
  const theme = cookieStore.get("theme");
  const lang = cookieStore.get("NEXT_LOCALE");

  return (
    <html lang={lang?.value ?? "en"}>
      <body>
        <Suspense>
          <AntdRegistry>
            <RefineContext themeMode={theme?.value}>{children}</RefineContext>
          </AntdRegistry>
        </Suspense>
      </body>
    </html>
  );
}
